### ISSUE TITLE
do_spdx throws unhandled exception if the SPDX_MANIFEST_DIR does not exist

### ISSUE THREAD

**Issue by dswright1990** [ttgurney/yocto-spdx#11]
Update 2015-2-17: Need to test this change.

The do_spdx code attempts to write to the directory specified by the bitbake variable SPDX_MANIFEST_DIR without verifying that the directory actually exists, and throws an unhandled exception if it doesn't exist. The code should create the whole needed directory tree if it does not exist (e.g. if SPDX_MANIFEST_DIR is specified as /home/yocto/fossology_scans and /home/yocto does not exist, both /home/yocto and /home/yocto/fossology_scans should be created automatically.)

**Comment by dswright1990** [comment]
I added the check_dir() method which checks to see if the /home/yocto/fossology_scans directory exists and if not creates it.

**Comment by ttgurney** [comment]
Needs to be corrected to use the variable SPDX_MANIFEST_DIR rather than the hardcoded "/home/yocto/fossology_scans"

**Comment by ttgurney** [comment]
Thanks Dan, you're the man.
Have you tested this change?

**Comment by dswright1990** [comment]
I have not

**Comment by ttgurney** [comment]
I tested this one and it failed because the function `check_dir()` had no idea what `manifest_dir` is. The variable `manifest_dir` was declared in another function so it was out of scope. I've since corrected it --and tested it.

This is why you must test even small changes!
