### ISSUE TITLE
Code Breakdown/Analysis

### ISSUE THREAD

**Issue by klumb** [ttgurney/yocto-spdx#18]
Could we set aside time during one of our meetings to do a line-by-line breakdown of the code?  It would be incredibly helpful for me.  I think it could help with our documentation as well.

**Comment by ttgurney** [comment]
Hah, we started doing this at the meeting before last, the one you and Dan didn't make it to! I think this is a great idea though; let's do it at tomorrow's meeting and then close this issue once we've gone through the whole thing.
