### ISSUE TITLE
Create - Work Breakdown/Group Structure/Code Contribution Management Plan

### ISSUE THREAD

**Issue by klumb** [ttgurney/yocto-spdx#21]

**Comment by klumb** [comment]
After looking at this closer, I am going to split these documents after all.  I will include information on our groups internal submission and code management in the work breakdown document.  The code contribution management plan will focus on external code submission policies.

**Comment by ttgurney** [comment]
My recommendation regarding code submission from people outside our team, is to put a document called "CONTRIBUTING.md" in the repository root with this information (it's a conventional place to look for that information)

**Comment by klumb** [comment]
Thanks.  I will use that naming convention.  I am modeling our document after Yocto. It will be a simpler version than Yocto but I will include a link to theirs as they are related.

**Comment by klumb** [comment]
These documents were both created.
