### ISSUE TITLE
Reinstall FOSSology on spdxdev

### ISSUE THREAD

**Issue by ttgurney** [ttgurney/yocto-spdx#22]
Need to reinstall FOSSology with SPDX plugin on spdxdev.ist.unomaha.edu (currently it's super broken)

**Comment by germonprez** [comment]
What is super broken?

**Comment by ttgurney** [comment]
Not sure yet... last time we tried to do a scan (via the web interface), FOSSology errored out immediately; we traced the issue to a missing table in the FOSSology database... but didn't document the name of the table. Will have to go back and check, and fill in the details on this issue as we find them.

**Comment by germonprez** [comment]
OK.

**Comment by ttgurney** [comment]
Donel here were the steps taken:
- drop database "fossology" from postgresql
- remove all fossology packages and reinstall with `sudo apt-get fossology`
- verify database connection and that web interface loads successfully
