### ISSUE TITLE
Review use cases and correct as needed

### ISSUE THREAD

**Issue by ttgurney** [ttgurney/yocto-spdx#25]
Use case 2 needs to be rewritten; the use of caching does not involve the user (it is an implementation detail) and it's out of scope for our project anyway (specifically, it is a DoSOCS implementation detail). So we need to come up with something else.

**Comment by ttgurney** [comment]
Made edits to use case 1 and updated this issue

**Comment by ttgurney** [comment]
I am having a hard time thinking of a second use case. There really is none. This is basically a batch process tool that does only thing only, and the only configurable behavior (at least at this point) is "where do I put the output." Perhaps I'm thinking too narrowly. Any suggestions, team?

**Comment by germonprez** [comment]
Is there only one way that a person will interact with the system?

Run / Don't Run

Might there be different choices a person could make within run/don't run?

matt

**Comment by dswright1990** [comment]
I imagine we will probably remove use case 2, I added use case 3 a possible use case regarding the database being created for the class.
