### ISSUE TITLE
Regarding contributor access (code contribution management)

### ISSUE THREAD

**Issue by ttgurney** [ttgurney/yocto-spdx#37]
@klumb: Do we REALLY want people outside the team to even have the chance to get commit access to this repo? I don't see the value in it to be honest, the good ol' fork-and-pull seems to be sufficient in our case.

**Comment by klumb** [comment]
It probably isn't necessary.  I really don't see us giving away that type of control right now.  It does add a method to change maintainers over time.  I have no issue removing it.

**Comment by ttgurney** [comment]
Ah, I hadn't thought about the eventual hand-off. I suppose it doesn't hurt to have it in there.
