### ISSUE TITLE
Create development branch for 'work in progress' code

### ISSUE THREAD

**Issue by ttgurney** [ttgurney/yocto-spdx#60]
Dan, please move your WIP code out of the master branch into a new dev branch and then merge the two once you are ready.

I know you've commented it out, but it's not really appropriate to have commented out code in our "production" version.

We should establish a convention that `master` is only for code that has been tested and is in a known good state with no half-finished work.

**Comment by dswright1990** [comment]
Cleaned the master branch of any WIP code.
