### ISSUE TITLE
Automate Installation

### ISSUE THREAD

**Issue by DanPatten** [ttgurney/yocto-spdx#62]
Just a few enhancements to consider during my setup:

1. Do not require the use to manually run 'source oe-init-build-env' - possibly have this executed at the end of the install script

2. Automatically insert "spdx" into USER_CLASSES (Also instructions were not clear as I had to try to find conf/local.conf file when it was actually located at /poky/build/conf/local.conf

**Comment by klumb** [comment]
1. The Yocto build process requires that you manually run 'source oe-init-build-env' every time you open a new shell.  We can not automate this.

2. The local.conf file is generated from the run source oe-init-build-env so it follows this can not be scripted either.

**Comment by plato360** [comment]
also on point 2, if you follow the instructions exactly, you should already be in the build directory where conf/local.conf is located
