### ISSUE TITLE
Yocto Dependencies

### ISSUE THREAD

**Issue by DanPatten** [ttgurney/yocto-spdx#63]
When running yocto for the first time I add to install several extra dependencies needed by yocto and was not sure of these dependencies until running a yocto build for the first time. You may want to add a list of dependencies that I can install ahead of time.

**Comment by klumb** [comment]
In our install instructions, we mention that the assumption is that the user is already using yocto.  Installing yocto is not in the scope of our project.  To make the process a little more user friendly, we have now added a link to the yocto getting started dependancies page on our install page.
