### ISSUE TITLE
Create list of test cases

### ISSUE THREAD

**Issue by ttgurney** [ttgurney/yocto-spdx#64]
Need a list of scenarios to be tested by our unit tests and the expected success and failure behavior for each scenario.

**Comment by dswright1990** [comment]
PrintType - changing the print type in licenses.conf to rdf, tag, and json should change the output format correctly. Also setting the print type to something like "asdf" should result in the output format in json

**Comment by dswright1990** [comment]
Using extra doSOCS flags

--creator
--creator_comment 
--document_comment 

In licenses.conf uncomment and set to the desired comment should include them in the spdx output

**Comment by dswright1990** [comment]
Output directory test

 spdx_manifest_dir in license.conf is the desired directory to save the spdx documents created during the build process. If desired directory doesn't exist it should be created and the results stored there. A possible fail case is if the variable is set to a directory that the user does not have write access to.

**Comment by ttgurney** [comment]
Looks good Dan. Closing this one.
