### ISSUE TITLE
Update DFD per Matt suggestions - 4/20

### ISSUE THREAD

**Issue by ttgurney** [ttgurney/yocto-spdx#68]
From Matt:
```
- Subtle issue in the DFD
  - does do_patch really send a document request to the create_tarball process?
    - are you modifying do_patch to do this? I'm curious about the relationship.
```
The reality, of course, is that `do_patch` doesn't send anything. There's no sending going on here. Bitbake starts the `do_spdx` task after `do_patch` completes. Either we need to indicate this somehow in the DFD (is it even appropriate for a DFD?) or just remove the erroneous information.

**Comment by klumb** [comment]
Updated!
