### ISSUE TITLE
Replace all instances of "Yocto-SPDX" with "Yocto+SPDX"

### ISSUE THREAD

**Issue by ttgurney** [ttgurney/yocto-spdx#70]
Let's be consistent!

**Comment by ttgurney** [comment]
They seem to all be taken care of, except for the slide deck @dswright1990 created.

**Comment by ttgurney** [comment]
Good enough.

**Comment by klumb** [comment]
I am updating the slide deck

**Comment by klumb** [comment]
Slide deck updated to reflect manual installation and yocto+SPDX
