### ISSUE TITLE
Update install to reflect "install.sh must be run from own directory"

### ISSUE THREAD

**Issue by jvosik** [ttgurney/yocto-spdx#72]
"The assumption at this point is that your current directory is poky and that the Yocto+SPDX repo is at ../yocto-spdx.

$ ../yocto-spdx/install.sh ."

---

This no longer works, as the install script must be run from inside yocto-spdx

**Comment by ttgurney** [comment]
Thanks for catching this one. We will update the install instructions.

**Comment by ttgurney** [comment]
Fixed!
