### ISSUE TITLE
[Doc] Markdown Documents Edit

### ISSUE THREAD

**Issue by klumb** [ttgurney/yocto-spdx#8]
I converted the documents to the markdown format.  Can someone take a look at them?  Please edit or add information if you feel it can improve the presentation.  The presentation has changed a little from the docx version.  Please close the issue if you  feel they are adequate.

**Comment by ttgurney** [comment]
Looking at this now.

**Comment by ttgurney** [comment]
Looks good Kev. Thanks again for picking this one up.
